### PR TITLE
Update runtime.txt to 3.7

### PR DESCRIPTION
**Pull request by carnei-ro**

### CODE REVIEW

**Comment by peaceiris** [comment]
> https://app.netlify.com/sites/mkdocs-material/deploys/5f862e892b28cc0008551fc1
>
> 7:47:51 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
> 7:47:51 AM: /usr/local/bin/run-build-functions.sh: line 168: /opt/buildhome/python3.7/bin/activate: No such file or directory
> 7:47:51 AM: Error setting python version from runtime.txt

Related to https://github.com/netlify/build-image/issues/431

**Comment by carnei-ro** [comment]
Just cloned your repo and try to configure Netlify - Same error for activate... when I changed to 3.7 it worked

**Comment by peaceiris** [comment]
I have changed the build image from Ubuntu 14 to 16.

Screen Shot 2020-10-14 at 8 01 18

**Comment by peaceiris** [comment]
It worked well! Thank you 👍

**Comment by carnei-ro** [comment]
Thank you!

**Pull request merged**
